default:
  server_name: lappis.rocks
  service_port: 80

rocketchat:
  server_name: chat.lappis.rocks
  service_port: 3000

boca:
  server_name: boca.lappis.rocks
  service_port: 80

portal:
  server_name: portal.lappis.rocks
  service_port: 3000

codeschool:
  server_name: codeschool.lappis.rocks
  service_port: 80

portalhomologa:
  server_name: portalhomologa.lappis.rocks
  service_port: 3000

sas:
  server_name: sas.lappis.rocks
  service_port: 8001

owla:
  server_name: owla.lappis.rocks
  service_port: 3000

